repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: debug-statements

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.11'
    hooks:
    -   id: ruff
        args: [
            --fix,
            --exit-non-zero-on-fix,
            --target-version, "py39",
            --select, "E,F,I,UP,N,B,A,C4,PT,RUF,SIM",
            --ignore, "E501"
        ]
