[project]
name = "test-cv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "langchain-openai>=0.3.14",
    "langgraph>=0.3.31",
    "redis>=5.2.1",
    "reportlab>=4.4.0",
]
